-- Enable RLS on all Phase 0 platform tables (direct ALTER TABLE, no helper)
ALTER TABLE "PlatformAuditLog"     ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PlatformAuditLog"     FORCE  ROW LEVEL SECURITY;

ALTER TABLE "OutboxEvent"          ENABLE ROW LEVEL SECURITY;
ALTER TABLE "OutboxEvent"          FORCE  ROW LEVEL SECURITY;

ALTER TABLE "InboxEvent"           ENABLE ROW LEVEL SECURITY;
ALTER TABLE "InboxEvent"           FORCE  ROW LEVEL SECURITY;

ALTER TABLE "Journal"              ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Journal"              FORCE  ROW LEVEL SECURITY;

ALTER TABLE "FiscalPeriod"         ENABLE ROW LEVEL SECURITY;
ALTER TABLE "FiscalPeriod"         FORCE  ROW LEVEL SECURITY;

ALTER TABLE "AccountGroup"         ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AccountGroup"         FORCE  ROW LEVEL SECURITY;

ALTER TABLE "Account"              ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Account"              FORCE  ROW LEVEL SECURITY;

ALTER TABLE "Document"             ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Document"             FORCE  ROW LEVEL SECURITY;

ALTER TABLE "AiCallLog"            ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AiCallLog"            FORCE  ROW LEVEL SECURITY;

ALTER TABLE "BusinessConfig"       ENABLE ROW LEVEL SECURITY;
ALTER TABLE "BusinessConfig"       FORCE  ROW LEVEL SECURITY;

ALTER TABLE "NumberSeries"         ENABLE ROW LEVEL SECURITY;
ALTER TABLE "NumberSeries"         FORCE  ROW LEVEL SECURITY;

ALTER TABLE "ComputationJob"       ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ComputationJob"       FORCE  ROW LEVEL SECURITY;

ALTER TABLE "BusinessRuleOverride" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "BusinessRuleOverride" FORCE  ROW LEVEL SECURITY;
