'use client';

import { TrendingUp, Package } from 'lucide-react';
import { BiText, BiHeading, BiBullet, InfoBox, Section, Card, SectionHeader } from '../../_shared';

export default function GSTRegisters() {
  return (
    <>
      {/* ── 5. SALES REGISTER ── */}
      <Section id="gst-sales">
        <Card>
          <SectionHeader icon={TrendingUp} num={5} en="Sales Register" te="సేల్స్ రిజిస్టర్" />
          <BiText className="mb-3"
            en="Every sale from POS and the online storefront appears here, split by invoice type (B2B / B2CL / B2CS), with full tax breakup. This is the source data for filing GSTR-1."
            te="POS మరియు ఆన్‌లైన్ స్టోర్‌ఫ్రంట్ నుండి ప్రతి అమ్మకం ఇన్వాయిస్ రకం వారీగా (B2B / B2CL / B2CS) పూర్తి పన్ను వివరాలతో ఇక్కడ కనిపిస్తుంది." />

          <BiHeading en="Invoice Types Explained" te="ఇన్వాయిస్ రకాలు వివరించబడ్డాయి" />
          <div className="space-y-2 mb-4">
            <div className="border border-blue-200 bg-blue-50 rounded-xl p-3">
              <p className="text-sm font-bold text-blue-800">B2B — Business to Business</p>
              <p className="text-xs text-blue-700 mt-1">Customer provided their GSTIN at billing. Full invoice is reported in GSTR-1 bill-by-bill. Customer can claim ITC on this purchase.</p>
              <p className="text-[11px] text-blue-600 mt-1" style={{ fontFamily: 'Noto Sans Telugu, sans-serif' }}>కస్టమర్ వారి GSTIN అందించారు. GSTR-1 లో బిల్లు వారీగా నివేదించబడుతుంది. కస్టమర్ ITC క్లెయిమ్ చేయవచ్చు.</p>
            </div>
            <div className="border border-amber-200 bg-amber-50 rounded-xl p-3">
              <p className="text-sm font-bold text-amber-800">B2CL — B2C Large (inter-state, value {'>'} ₹2.5 lakh)</p>
              <p className="text-xs text-amber-700 mt-1">No GSTIN, the sale is to a customer in a DIFFERENT state (inter-state), AND single invoice value exceeds ₹2.5 lakh. Reported invoice-wise in GSTR-1. Note: intra-state sales above ₹2.5L without GSTIN still go into B2CS, not B2CL.</p>
              <p className="text-[11px] text-amber-600 mt-1" style={{ fontFamily: 'Noto Sans Telugu, sans-serif' }}>GSTIN లేదు, వేరే రాష్ట్రంలో కస్టమర్, మరియు ఒకే ఇన్వాయిస్ విలువ ₹2.5 లక్షలు మించింది. అదే రాష్ట్రంలో ₹2.5L పైన అమ్మకాలు కూడా B2CS లోకి వెళ్తాయి.</p>
            </div>
            <div className="border border-gray-200 bg-gray-50 rounded-xl p-3">
              <p className="text-sm font-bold text-gray-700">B2CS — B2C Small (value ≤ ₹2.5 lakh, most retail)</p>
              <p className="text-xs text-gray-600 mt-1">No GSTIN and invoice value is ₹2.5 lakh or below. Reported as a combined summary (not bill-by-bill) in GSTR-1. This covers most daily retail sales.</p>
              <p className="text-[11px] text-gray-500 mt-1" style={{ fontFamily: 'Noto Sans Telugu, sans-serif' }}>GSTIN లేదు మరియు ఇన్వాయిస్ విలువ ₹2.5 లక్షలు లేదా అంతకంటే తక్కువ. GSTR-1 లో సమిష్టి సారాంశంగా నివేదించబడుతుంది. ఇది చాలా రోజువారీ రిటైల్ అమ్మకాలను కవర్ చేస్తుంది.</p>
            </div>
          </div>

          <BiHeading en="Intra-state vs Inter-state Tax" te="రాష్ట్రంలో vs వేరే రాష్ట్రం పన్ను" />
          <div className="grid md:grid-cols-2 gap-3 mb-3">
            <div className="bg-green-50 border border-green-200 rounded-lg p-3">
              <p className="text-xs font-bold text-green-800 mb-1">Intra-state sale (same state)</p>
              <p className="text-xs text-green-700">Taxable value split into <strong>CGST + SGST</strong>, each at half the GST rate.</p>
              <p className="text-[11px] text-green-600 mt-1 font-mono">18% GST → CGST 9% + SGST 9%<br />12% GST → CGST 6% + SGST 6%</p>
            </div>
            <div className="bg-blue-50 border border-blue-200 rounded-lg p-3">
              <p className="text-xs font-bold text-blue-800 mb-1">Inter-state sale (different state)</p>
              <p className="text-xs text-blue-700">Only <strong>IGST</strong> applies at the full rate. No CGST/SGST.</p>
              <p className="text-[11px] text-blue-600 mt-1 font-mono">18% GST → IGST 18%<br />12% GST → IGST 12%</p>
            </div>
          </div>

          <BiHeading en="Column Guide" te="కాలమ్ గైడ్" />
          <ul className="list-none pl-0">
            <BiBullet en="Invoice No: Unique bill number generated by ERP at the time of sale" te="ఇన్వాయిస్ నం: అమ్మకం సమయంలో ERP రూపొందించిన ప్రత్యేక బిల్లు నంబర్" />
            <BiBullet en="GSTIN/UIN: Customer's GST registration number (B2B only; blank for B2C)" te="GSTIN/UIN: కస్టమర్ యొక్క GST నమోదు నంబర్ (B2B మాత్రమే; B2C కోసం ఖాళీగా ఉంటుంది)" />
            <BiBullet en="Taxable Value: Sale amount before GST. This is what goes into GSTR-3B Table 3.1(a)" te="పన్ను విలువ: GST కి ముందు అమ్మకం మొత్తం. ఇది GSTR-3B పట్టిక 3.1(a) లోకి వెళ్తుంది" />
            <BiBullet en="CGST / SGST / IGST: Actual tax amounts in rupees for that invoice" te="CGST / SGST / IGST: ఆ ఇన్వాయిస్ కోసం రూపాయల్లో వాస్తవ పన్ను మొత్తాలు" />
            <BiBullet en="Total: Taxable value + all tax amounts = amount customer actually paid" te="మొత్తం: పన్ను విలువ + అన్ని పన్ను మొత్తాలు = కస్టమర్ వాస్తవంగా చెల్లించిన మొత్తం" />
          </ul>
          <InfoBox color="green"
            en="The 'Total Output Tax' card at the top of GSTR-3B Summary = sum of all CGST + SGST + IGST from this register."
            te="GSTR-3B సారాంశం పైన 'మొత్తం అవుట్‌పుట్ పన్ను' కార్డ్ = ఈ రిజిస్టర్ నుండి అన్ని CGST + SGST + IGST మొత్తం." />
        </Card>
      </Section>

      {/* ── 6. PURCHASE REGISTER ── */}
      <Section id="gst-purchase">
        <Card>
          <SectionHeader icon={Package} num={6} en="Purchase Register" te="పర్చేస్ రిజిస్టర్" />
          <BiText className="mb-3"
            en="Every GRN (Goods Receipt Note) approved in the system appears here. This is your complete purchase record with ITC eligibility — the source for claiming Input Tax Credit."
            te="సిస్టమ్‌లో ఆమోదించబడిన ప్రతి GRN ఇక్కడ కనిపిస్తుంది. ఇది ITC అర్హతతో మీ పూర్తి కొనుగోలు రికార్డ్ — ఇన్‌పుట్ ట్యాక్స్ క్రెడిట్ క్లెయిమ్ చేయడానికి మూలం." />

          <BiHeading en="Column Guide" te="కాలమ్ గైడ్" />
          <ul className="list-none pl-0">
            <BiBullet en="Supplier GSTIN: The supplier's GST registration number. Mandatory for ITC claim — you cannot claim ITC if the supplier has no GSTIN." te="సప్లయర్ GSTIN: సప్లయర్ యొక్క GST నమోదు నంబర్. ITC క్లెయిమ్ కోసం తప్పనిసరి — సప్లయర్‌కు GSTIN లేకపోతే ITC క్లెయిమ్ చేయలేరు." />
            <BiBullet en="Invoice No / Date: Must exactly match the supplier's actual invoice — GSTportal will reject if there's a mismatch during GSTR-2B reconciliation." te="ఇన్వాయిస్ నం / తేదీ: సప్లయర్ యొక్క వాస్తవ ఇన్వాయిస్‌తో సరిగ్గా సరిపోలాలి — GSTR-2B రికన్సిలియేషన్ సమయంలో వ్యత్యాసం ఉంటే GST పోర్టల్ తిరస్కరిస్తుంది." />
            <BiBullet en="Taxable Value: Purchase amount before GST — this is the base on which ITC is calculated." te="పన్ను విలువ: GST కి ముందు కొనుగోలు మొత్తం — ఇది ITC లెక్కించబడే ఆధారం." />
            <BiBullet en="CGST + SGST or IGST: Tax paid to supplier — this is what you want to recover as ITC (if eligible)." te="CGST + SGST లేదా IGST: సప్లయర్‌కు చెల్లించిన పన్ను — ఇది మీరు ITC గా తిరిగి పొందాలనుకునే మొత్తం." />
            <BiBullet en="ITC Eligibility: ELIGIBLE (can claim) / EXEMPT (0% GST, nothing to claim) / NOT_ELIGIBLE (Sec 17(5) blocked)." te="ITC అర్హత: ELIGIBLE (క్లెయిమ్ చేయవచ్చు) / EXEMPT (0% GST) / NOT_ELIGIBLE (Sec 17(5) నిరోధించబడింది)." />
          </ul>

          <BiHeading en="How to reconcile with GSTR-2B" te="GSTR-2B తో ఎలా రికన్సైల్ చేయాలి" />
          <div className="space-y-2 mb-3">
            {[
              { step: '1', text: "Download GSTR-2B from the GST portal for the same month (Login → Returns → GSTR-2B → Download JSON / View).", te: 'అదే నెల కోసం GST పోర్టల్ నుండి GSTR-2B డౌన్‌లోడ్ చేయండి.' },
              { step: '2', text: "Compare supplier GSTIN and invoice numbers between GSTR-2B and the ERP Purchase Register.", te: 'GSTR-2B మరియు ERP పర్చేస్ రిజిస్టర్ మధ్య సప్లయర్ GSTIN మరియు ఇన్వాయిస్ నంబర్లు పోల్చండి.' },
              { step: '3', text: "Invoice in ERP but NOT in GSTR-2B → supplier has not filed GSTR-1. Follow up. ITC unavailable for now.", te: 'ERP లో ఉంది కానీ GSTR-2B లో లేదు → సప్లయర్ GSTR-1 దాఖలు చేయలేదు. ITC ప్రస్తుతానికి అందుబాటులో లేదు.' },
              { step: '4', text: "Invoice in GSTR-2B but NOT in ERP → missed GRN entry. Enter the GRN in ERP before filing.", te: 'GSTR-2B లో ఉంది కానీ ERP లో లేదు → GRN నమోదు మిస్ అయింది. దాఖలు చేయడానికి ముందు ERP లో GRN నమోదు చేయండి.' },
              { step: '5', text: "Claim ITC only for invoices confirmed in GSTR-2B. Do not claim for unmatched invoices.", te: 'GSTR-2B లో నిర్ధారించబడిన ఇన్వాయిస్‌లకు మాత్రమే ITC క్లెయిమ్ చేయండి.' },
            ].map(({ step, text, te }) => (
              <div key={step} className="flex gap-3 items-start">
                <span className="w-5 h-5 rounded-full bg-emerald-700 text-white flex items-center justify-center text-[10px] font-bold shrink-0 mt-0.5">{step}</span>
                <div>
                  <p className="text-xs text-gray-800 leading-relaxed">{text}</p>
                  <p className="text-[11px] text-gray-500 mt-0.5" style={{ fontFamily: 'Noto Sans Telugu, sans-serif' }}>{te}</p>
                </div>
              </div>
            ))}
          </div>
          <InfoBox color="amber"
            en="Run this reconciliation every month BEFORE filing GSTR-3B. Claiming ITC for invoices not in GSTR-2B can lead to notices and demand of ITC reversal with interest."
            te="GSTR-3B దాఖలు చేయడానికి ముందు ప్రతి నెలా ఈ రికన్సిలియేషన్ నిర్వహించండి. GSTR-2B లో లేని ఇన్వాయిస్‌లకు ITC క్లెయిమ్ చేయడం నోటీసులకు దారితీయవచ్చు." />
          <InfoBox color="red"
            en="Rule 37A — ITC Reversal: If a supplier files GSTR-1 but does NOT file their GSTR-3B, the GST system will automatically reverse any ITC you claimed from their invoices. You get the ITC back when they eventually file. This is why supplier GSTR-3B filing compliance matters, not just GSTR-1."
            te="Rule 37A: సప్లయర్ GSTR-1 దాఖలు చేసి GSTR-3B దాఖలు చేయకపోతే, GST సిస్టమ్ వారి ఇన్వాయిస్‌ల నుండి మీరు క్లెయిమ్ చేసిన ITC ని స్వయంచాలకంగా రివర్స్ చేస్తుంది. వారు చివరికి దాఖలు చేసినప్పుడు ITC తిరిగి వస్తుంది." />
        </Card>
      </Section>
    </>
  );
}
